### ISSUE TITLE
Tests missing

### ISSUE THREAD

**Issue by Miss-Cheese** [learn-co-curriculum/partial-locals-reading#24]
I know it's a readme lab, usually there are some tests though, and a way to submit it. Here, there's nothing.. and I can't mark it ad 'Read' because it behaves like a lab. How can I run tests and mark it as done & submitted?

<img width="260" alt="Screen Shot 2019-12-22 at 20 10 54" src="https://user-images.githubusercontent.com/57041056/71329855-4b798a80-24f7-11ea-8d89-427ef6a03c86.png">

**Comment by Sdcrouse** [comment]
I agree. I can't submit the lesson either. Not only that, but the entire second half of the README ("The Problem") contradicts the first half!

**Comment by maxwellbenton** [comment]
Hi @Miss-Cheese,

Thank you for reporting this issue! We've updated this lesson so that it will be interpreted in Learn as a code-along for future students (no tests need to be passed, just a submission of work), which should resolve this issue.

Thank you for contributing to the Learn Curriculum!

**Comment by Miss-Cheese** [comment]
Hi Maxwell, thank you for looking into this! I've re-forked and re-cloned the lab and coded along again. Though tests aren't required anymore, I still couldn't submit the lab, 'Learn Submit' didn't work, and I couldn't mark it as read either. Attaching couple of screenshots:

<img width="272" alt="Screen Shot 2019-12-27 at 19 21 27" src="https://user-images.githubusercontent.com/57041056/71536524-5dd03b80-28de-11ea-833c-d824019c6c61.png">

<img width="525" alt="Screen Shot 2019-12-27 at 19 21 56" src="https://user-images.githubusercontent.com/57041056/71536527-67f23a00-28de-11ea-8ddb-79721a2f2e11.png">

**Comment by maxwellbenton** [comment]
Hi @Miss-Cheese,

I'm sorry to hear! I've taken another look, but I was unable to replicate what you experienced - `learn submit` is working currently from what I can tell. I have a feeling this issue is due to you already forking the lesson. Learn tracks lesson progress separately from the GitHub repositories, so it may be that because you had forked the lesson when it was considered a lab, it won't work as intended now. I'm unfortunately unable to confirm though.

**Comment by Sdcrouse** [comment]
I haven't re-forked and cloned the lesson from learn-co-students, but I did re-fork and clone it from the learn-co-curriculum. I still get that `learn: command not found` error. I will see if the same happens with the learn-co-students version.

**Comment by Sdcrouse** [comment]
Update: I re-forked and cloned the lesson from the learn-co-students repository as well. I'm getting the same error as before:

![image](https://user-images.githubusercontent.com/38870640/71637267-53ba7f80-2bf3-11ea-94e8-6b6ef463b110.png)

@Miss-Cheese and @maxwellbenton is it possible that this bug is only happening with certain local environments? I'm using WSL with Ubuntu and VSCode.
